Checks if chosen input file is a valid ssh public key. Supports rsa, dsa, ecdsa.
This check doesn't include ed25519 ssh type. Although this type is supported by ssh-keygen,
it's not recognized as valid by the 'file' command.
	$ file id_ed25519
	id_ed25519: ASCII text

Furthermore a valid id_ed25519 key file in ~/.ssh/ will not permit adding new admin user with
the 'leap add-user --self' command, throwing :
	error: Could not parse PKey: no start line
possibly related with capistrano gem.